//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalePoint.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class forma_pagamento
    {
        public int pgt_id_forma_pagamento { get; set; }
        public string pgt_ds_forma_pagamento { get; set; }
    }
}
