//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalePoint.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int pro_id_produto { get; set; }
        public string pro_ds_produto { get; set; }
        public int pro_id_categoria { get; set; }
        public double pro_ds_preco { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
